# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

canny_edge_detector <- function(image, X, Y, s = 2, low_thr = 3, high_thr = 10, accGrad = FALSE) {
    .Call('_image_CannyEdges_canny_edge_detector', PACKAGE = 'image.CannyEdges', image, X, Y, s, low_thr, high_thr, accGrad)
}

