# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_contours <- function(image, X, Y, Q = 2.0) {
    .Call('_image_ContourDetector_detect_contours', PACKAGE = 'image.ContourDetector', image, X, Y, Q)
}

