# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

openpano_stitch <- function(x, file_config, file_out) {
    .Call('_image_OpenPano_openpano_stitch', PACKAGE = 'image.OpenPano', x, file_config, file_out)
}

