# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_corners <- function(x, width, height, bytes_per_row, suppress_non_max = FALSE, threshold = 4L) {
    .Call('_image_CornerDetectionF9_detect_corners', PACKAGE = 'image.CornerDetectionF9', x, width, height, bytes_per_row, suppress_non_max, threshold)
}

