# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

otsu <- function(x, width, height, threshold = 0L) {
    .Call('_image_Otsu_otsu', PACKAGE = 'image.Otsu', x, width, height, threshold)
}

