# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_faces <- function(x, width, height, step) {
    .Call('_image_libfacedetection_detect_faces', PACKAGE = 'image.libfacedetection', x, width, height, step)
}

