library(magick)
x <- image_read(path = "image.CornerDetectionHarris/dev/building.png")
x <- image_convert(x, colorspace = "Gray")
x <- image_scale(x, "500!x500!")
x
img <- image_data(x)
img <- as.integer(img, transpose = TRUE)
img <- as.vector(img[, , 1])
points <- image.CornerDetectionHarris:::detect_corners(img, 500, 500)

library(pixmap)
f <- tempfile(fileext = ".pgm")
image_write(x, path = f, format = "pgm")
image <- read.pnm(f, cellres = 1)
plot(image)
points(points$y, 500-points$x, col = "red", pch = 20, lwd = 0.5)
