# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_line_segments <- function(image, X, Y, scale = 0.8, sigma_scale = 0.6, quant = 2.0, ang_th = 22.5, log_eps = 0.0, density_th = 0.7, n_bins = 1024L, need_to_union = 0L, union_ang_th = 7, union_use_NFA = 0L, union_log_eps = 0.0, length_threshold = 5, dist_threshold = 5) {
    .Call('_image_LineSegmentDetector_detect_line_segments', PACKAGE = 'image.LineSegmentDetector', image, X, Y, scale, sigma_scale, quant, ang_th, log_eps, density_th, n_bins, need_to_union, union_ang_th, union_use_NFA, union_log_eps, length_threshold, dist_threshold)
}

