// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// openpano_stitch
Rcpp::List openpano_stitch(Rcpp::StringVector x, const char* file_config, const char* file_out);
RcppExport SEXP _image_OpenPano_openpano_stitch(SEXP xSEXP, SEXP file_configSEXP, SEXP file_outSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const char* >::type file_config(file_configSEXP);
    Rcpp::traits::input_parameter< const char* >::type file_out(file_outSEXP);
    rcpp_result_gen = Rcpp::wrap(openpano_stitch(x, file_config, file_out));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_image_OpenPano_openpano_stitch", (DL_FUNC) &_image_OpenPano_openpano_stitch, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_image_OpenPano(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
