# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dlib_fhog <- function(x, rows, cols, cell_size = 8L, filter_rows_padding = 1L, filter_cols_padding = 1L) {
    .Call('_image_dlib_dlib_fhog', PACKAGE = 'image.dlib', x, rows, cols, cell_size, filter_rows_padding, filter_cols_padding)
}

dlib_surf_points <- function(x, rows, cols, max_points = 10000L, detection_threshold = 30.0) {
    .Call('_image_dlib_dlib_surf_points', PACKAGE = 'image.dlib', x, rows, cols, max_points, detection_threshold)
}

