// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
// [[Rcpp::depends(dlib)]]
// [[Rcpp::plugins(cpp11)]]

using namespace Rcpp;

// dlib_fhog
List dlib_fhog(const std::string file, const int cell_size, const int filter_rows_padding, const int filter_cols_padding);
RcppExport SEXP image_dlib_dlib_fhog(SEXP fileSEXP, SEXP cell_sizeSEXP, SEXP filter_rows_paddingSEXP, SEXP filter_cols_paddingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< const int >::type cell_size(cell_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type filter_rows_padding(filter_rows_paddingSEXP);
    Rcpp::traits::input_parameter< const int >::type filter_cols_padding(filter_cols_paddingSEXP);
    rcpp_result_gen = Rcpp::wrap(dlib_fhog(file, cell_size, filter_rows_padding, filter_cols_padding));
    return rcpp_result_gen;
END_RCPP
}
// dlib_surf_points
List dlib_surf_points(const std::string file_name, long max_points, double detection_threshold);
RcppExport SEXP image_dlib_dlib_surf_points(SEXP file_nameSEXP, SEXP max_pointsSEXP, SEXP detection_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type file_name(file_nameSEXP);
    Rcpp::traits::input_parameter< long >::type max_points(max_pointsSEXP);
    Rcpp::traits::input_parameter< double >::type detection_threshold(detection_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(dlib_surf_points(file_name, max_points, detection_threshold));
    return rcpp_result_gen;
END_RCPP
}
