# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_corners <- function(x, nx, ny, k = 0.060000, sigma_d = 1.000000, sigma_i = 2.500000, threshold = 130, gaussian = 1L, gradient = 0L, strategy = 0L, Nselect = 1L, measure = 0L, Nscales = 1L, precision = 1L, cells = 10L, verbose = 1L) {
    .Call('_image_CornerDetectionHarris_detect_corners', PACKAGE = 'image.CornerDetectionHarris', x, nx, ny, k, sigma_d, sigma_i, threshold, gaussian, gradient, strategy, Nselect, measure, Nscales, precision, cells, verbose)
}

