// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// detect_corners
List detect_corners(IntegerVector x, int width, int height, int bytes_per_row, bool suppress_non_max, unsigned char threshold);
RcppExport SEXP _image_CornerDetectionF9_detect_corners(SEXP xSEXP, SEXP widthSEXP, SEXP heightSEXP, SEXP bytes_per_rowSEXP, SEXP suppress_non_maxSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type width(widthSEXP);
    Rcpp::traits::input_parameter< int >::type height(heightSEXP);
    Rcpp::traits::input_parameter< int >::type bytes_per_row(bytes_per_rowSEXP);
    Rcpp::traits::input_parameter< bool >::type suppress_non_max(suppress_non_maxSEXP);
    Rcpp::traits::input_parameter< unsigned char >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_corners(x, width, height, bytes_per_row, suppress_non_max, threshold));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_image_CornerDetectionF9_detect_corners", (DL_FUNC) &_image_CornerDetectionF9_detect_corners, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_image_CornerDetectionF9(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
