# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_nlmeans <- function(image, width, height, channels, sigma, args_auto = TRUE, win = 1L, bloc = 10L, fFiltPar = 0.4) {
    .Call('_image_DenoiseNLMeans_rcpp_nlmeans', PACKAGE = 'image.DenoiseNLMeans', image, width, height, channels, sigma, args_auto, win, bloc, fFiltPar)
}

